"""user_deck column updates

Revision ID: 0c8facfeee7f
Revises: 9a8c8f26d094
Create Date: 2023-12-18 18:06:33.553346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8facfeee7f'
down_revision = '9a8c8f26d094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'decks', ['deck_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deck_id')

    # ### end Alembic commands ###
