"""update user_deck columns

Revision ID: 11ec93169d03
Revises: c5613befd500
Create Date: 2023-12-21 13:25:46.818123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ec93169d03'
down_revision = 'c5613befd500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_deck_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('deck_cards_deck_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_decks', ['user_deck_id'], ['id'])
        batch_op.drop_column('deck_id')

    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.drop_constraint('user_decks_deck_card_id_fkey', type_='foreignkey')
        batch_op.drop_column('deck_card_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_decks_deck_card_id_fkey', 'deck_cards', ['deck_card_id'], ['id'])

    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deck_cards_deck_id_fkey', 'decks', ['deck_id'], ['id'])
        batch_op.drop_column('user_deck_id')

    # ### end Alembic commands ###
