"""changing db

Revision ID: 9a8c8f26d094
Revises: 
Create Date: 2023-12-12 12:27:43.739703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8c8f26d094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint('decks_card_id_fkey', type_='foreignkey')
        batch_op.drop_column('card_id')

    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_card_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_decks_deck_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'deck_cards', ['deck_card_id'], ['id'])
        batch_op.drop_column('deck_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_decks_deck_id_fkey', 'decks', ['deck_id'], ['id'])
        batch_op.drop_column('deck_card_id')

    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('decks_card_id_fkey', 'cards', ['card_id'], ['id'])

    op.drop_table('deck_cards')
    # ### end Alembic commands ###
