"""column updates

Revision ID: c5613befd500
Revises: 0c8facfeee7f
Create Date: 2023-12-20 14:13:45.113469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5613befd500'
down_revision = '0c8facfeee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_deck_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('deck_cards_deck_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_decks', ['user_deck_id'], ['id'])
        batch_op.drop_column('deck_id')

    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_name', sa.String(length=50), nullable=True))
        batch_op.drop_constraint('user_decks_deck_card_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'decks', ['deck_name'], ['deck_name'])
        batch_op.drop_column('deck_card_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_decks_deck_card_id_fkey', 'deck_cards', ['deck_card_id'], ['id'])
        batch_op.drop_column('deck_name')

    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('deck_cards_deck_id_fkey', 'decks', ['deck_id'], ['id'])
        batch_op.drop_column('user_deck_id')

    # ### end Alembic commands ###
